# This file defines the configuration for the rake build task, which is responsible for building application code to
# be deployed on the production hosts.
#
# All paths are relative to the root directory (the one containing the Rakefile)
#
# Dependencies is a glob (see Ruby doc for Dir.glob) that specifies the dependencies of the output file.
#
# The build_script should be executable, and should, when run from the root directory, create the output file which is
# the key of the build output definition.
build_outputs:
    source/code/files/service_watcher.tar.xz:
        dependencies:
            - source/apps/ServiceWatcher/**
        build_script: |
            #!/bin/bash
            cd source/apps/ServiceWatcher
            make
        groups: [ python, service_watcher ]
