# This file defines the configuration for the rake build task, which is responsible for building application code to
# be deployed on the production hosts.
#
# All paths are relative to the root directory (the one containing the Rakefile)
#
# Dependencies is a glob (see Ruby doc for Dir.glob) that specifies the dependencies of the output file.
#
# The build_script should be executable, and should, when run from the root directory, create the output file which is
# the key of the build output definition.
build_outputs:
  source/code/files/service_watcher.tar.xz:
    dependencies:
      - source/apps/ServiceWatcher/**/*
    build_script: |
      #!/bin/bash
      set -euo pipefail
      cd source/apps
      tar --exclude=.idea --exclude='*.pyc' -cJvf ../code/files/service_watcher.tar.xz ServiceWatcher
    groups: [ python, service_watcher ]
  source/code/files/KafkaConsoleBridge.jar:
    enabled: false
    dependencies:
      - source/apps/FlinkProcess/KafkaToConsole/src/**/*
      - source/apps/FlinkProcess/KafkaToConsole/pom.xml
    build_script: |
      #!/bin/bash
      set -euo pipefail
      (cd source/apps/FlinkProcess/KafkaToConsole && mvn package)
      cp source/apps/FlinkProcess/KafkaToConsole/target/flink-kafka-to-console-0.1.jar source/code/files/KafkaConsoleBridge.jar
    groups: [ java, kafka_to_console, flink_process ]
  source/code/files/KafkaHbaseBridge.jar:
    dependencies:
      - source/apps/FlinkProcess/KafkaToHBase/src/**/*
      - source/apps/FlinkProcess/KafkaToHBase/pom.xml
    build_script: |
      #!/bin/bash
      set -euo pipefail
      (cd source/apps/FlinkProcess/KafkaToHBase && mvn package)
      cp source/apps/FlinkProcess/KafkaToHBase/target/flink-kafka-hbase-bridge-0.1.jar source/code/files/KafkaHbaseBridge.jar
    groups: [ java, kafka_to_hbase, flink_process ]
  source/code/files/FakeTwitterProducer.jar:
    dependencies:
      - source/apps/FlinkProducer/FakeTwitter/src/**/*
      - source/apps/FlinkProducer/FakeTwitter/pom.xml
    build_script: |
      #!/bin/bash
      set -euo pipefail
      (cd source/apps/FlinkProducer/FakeTwitter && mvn package)
      cp source/apps/FlinkProducer/FakeTwitter/target/flink-producer-fake-twitter-0.1.jar source/code/files/FakeTwitterProducer.jar
    groups: [ java, fake_twitter, flink_producer ]
  source/code/files/fake_tweet.json:
    dependencies:
      - source/apps/FlinkProducer/FakeTwitter/fake_tweet.json
    build_script: |
      #!/bin/bash
      set -euo pipefail
      cp source/apps/FlinkProducer/FakeTwitter/fake_tweet.json source/code/files/fake_tweet.json
    groups: [ seed_data ]
  source/code/files/TwitterProducer.jar:
    dependencies:
      - source/apps/FlinkProducer/RealTwitter/src/**/*
      - source/apps/FlinkProducer/RealTwitter/pom.xml
    build_script: |
      #!/bin/bash
      set -euo pipefail
      (cd source/apps/FlinkProducer/RealTwitter && mvn package)
      cp source/apps/FlinkProducer/RealTwitter/target/flink-producer-twitter-0.1.jar source/code/files/TwitterProducer.jar
    groups: [ java, twitter_producer, flink_producer ]
