# This file defines hostnames, usernames, ip addresses and private keys
# to use for connecting to the different servers using SSH.
#
# Default config options, referenced using YAML syntax
defaults:
    # Default options for hosts
    hosts: &host_defaults
        user: xnet     # Default non-privileged user
        key: keys/xnet # Identity file for SSH connection
# Known services definitions
services:
    - zookeeper
    - kafka
    - flink
    - hbase
    - zeppelin
    - flink_paris
    - flink_london
    - flink_nyc
    - flink_producer_fake
# Deployment specifications
deploy:
    shared_args:
    # List of provisioning steps, follows the same conventions as vagrant-hosts.yml
    provision:
        - hosts: $hostspec
        - ssh: $hostspec
        - apt:
        - java:
        - kafka: $hostspec
        # Not yet functioning on non-vagrant hosts
        # - flink: -t paris -t london -t nyc -q $hoststring
        # - hbase: -q $hoststring
        # - zeppelin:
    # List of source folders to include in the ~/deploy directory when provision
    # Note that the *contents* of mentioned directories are copied in the deploy
    # directory
    provision_folders:
        - source/provision
        - keys
    configure_folders:
        - source/configure
# One-shot run command specifications
run:
    format_hdfs: /usr/local/hadoop/bin/hdfs namenode -format
# Hosts definitions
hosts:
    server-1:
        <<: *host_defaults
        ip: 213.32.77.17
        services: # List of services to enable/start on server-1
            - zookeeper
            - kafka
            # - flink
            # - hbase
            # - flink_paris
            # - flink_producer_fake
        configure:
            after:
                - create_topics: "-t paris -t london -t nyc"
    server-2:
        <<: *host_defaults
        ip: 213.32.77.173
        services: # List of services to enable/start on server-2
            - zookeeper
            - kafka
            # - flink
            # - hbase
            # - flink_london
    server-3:
        <<: *host_defaults
        ip: 213.32.77.170
        services: # List of services to enable/start on server-3
            - zookeeper
            - kafka
            # - flink
            # - hbase
            # - flink_nyc
