# This file defines hostnames, usernames, ip addresses and private keys
# to use for connecting to the different servers using SSH.
#
# Default config options, referenced using YAML syntax
defaults:
    # Default options for hosts
    hosts: &host_defaults
        user: xnet     # Default non-privileged user
        key: keys/xnet # Identity file for SSH connection
# Known services definitions
services:
    - zookeeper
    - kafka
    - flink
    - hbase
    - zeppelin
    - flink_paris
    - flink_london
    - flink_nyc
    - flink_producer_fake
# Hosts definitions
hosts:
    server-1:
        <<: *host_defaults
        ip: 213.32.77.17
        services: # List of services to enable/start on server-1
            - zookeeper
            - kafka
            # - flink
            # - hbase
            # - flink_paris
            # - flink_producer_fake
        provisioning:
            before:
            after:
        configuring:
            before:
            after:
                - create_topics: "-t paris -t london -t nyc"
    server-2:
        <<: *host_defaults
        ip: 213.32.77.173
        services: # List of services to enable/start on server-2
            - zookeeper
            - kafka
            # - flink
            # - hbase
            # - flink_london
        provisioning:
            before:
            after:
        configuring:
            before:
            after:
    server-3:
        <<: *host_defaults
        ip: 213.32.77.170
        services: # List of services to enable/start on server-3
            - zookeeper
            - kafka
            # - flink
            # - hbase
            # - flink_nyc
        provisioning:
            before:
            after:
        configuring:
            before:
            after:
# List of provisioning steps, follows the same conventions as vagrant-hosts.yml
provisioning:
    - hosts: $hostspec
    - ssh: $hostspec
    - apt:
    - java:
    - kafka: $hostspec
    # Not yet functioning on non-vagrant hosts
    # - flink: -t paris -t london -t nyc
    # - hbase:
    # - zeppelin:
configuring:
shared_args:
shared_configure_args:
shared_script: source/install/provisioning_shared.sh
shared_configure_script: source/configure/configure_shared.sh
# List of source folders to include in the ~/deploy directory when provisioning
# Note that the *contents* of mentioned directories are copied in the deploy
# directory
source_folders:
    - source/install
    - keys
    # - source/deploy
configure_folders:
    - source/configure
