# This file defines hostnames, usernames, ip addresses and private keys
# to use for connecting to the different servers using SSH.
hosts:
    server-1:
        user: xnet
        ip: 213.32.77.17
        key: keys/xnet
    server-2:
        user: xnet
        ip: 213.32.77.173
        key: keys/xnet
    server-3:
        user: xnet
        ip: 213.32.77.170
        key: keys/xnet
provisioning:
    - apt:
    - java:
    - kafka:
    # - flink:
    # - hbase:
    # - zeppelin:
source_folders:
    - source/install
