# This file defines hostnames, usernames, ip addresses and private keys
# to use for connecting to the different servers using SSH.
#
# Default config options, referenced using YAML syntax
defaults:
  # Default options for hosts
  hosts: &host_defaults
    user: xnet     # Default non-privileged user
    key: keys/xnet # Identity file for SSH connection
# Known services definitions
services:
  - zookeeper
  - kafka
# Deployment specifications
deploy:
  variables:
    hostspec: '<%= hosts.map { |h| "-H #{h.name}@#{h.address}" }.join(" ") %>'
  shared_args:
  # List of provisioning steps, follows the same conventions as vagrant-hosts.yml
  bootstrap:
    - hosts: $hostspec
    - ssh: $hostspec
  system:
    - apt:
    - java:
    - python:
  # Not yet functioning on non-vagrant hosts: flink, hbase, zeppelin
  software:
    - kafka:
  settings:
    - kafka: $hostspec
  code:
  # List of source folders to include in the ~/deploy directory when provision
  # Note that the *contents* of mentioned directories are copied in the deploy
  # directory
  bootstrap_folders:
    - source/shared
    - source/bootstrap
    - keys
  system_folders:
    - ../source/shared
    - ../source/system
  software_folders:
    - source/shared
    - source/software
  settings_folders:
    - source/shared
    - source/settings
  code_folders:
    - source/shared
    - source/code
  configure_folders:
    - source/shared
    - source/configure
# One-shot run command specifications
run:
  format_hdfs: /usr/local/hadoop/bin/hdfs namenode -format
# Hosts definitions
hosts:
  server-1:
    <<: *host_defaults
    ip: 213.32.77.17
    services: # List of services to enable/start on server-1
      - zookeeper
      - kafka
    configure:
      after:
        - create_topics: "-t paris -t london -t nyc"
  server-2:
    <<: *host_defaults
    ip: 213.32.77.173
    services: # List of services to enable/start on server-2
      - zookeeper
      - kafka
  server-3:
    <<: *host_defaults
    ip: 213.32.77.170
    services: # List of services to enable/start on server-3
      - zookeeper
      - kafka
