---
# This file defines hostnames, usernames, ip addresses and private keys
# to use for connecting to the different servers using SSH.
#
# Default config options, referenced using YAML syntax
defaults:
  # Default options for hosts
  hosts: &host_defaults
    user: xnet     # Default non-privileged user
    key: keys/xnet # Identity file for SSH connection
# List of enabled services
services:
  - zookeeper
  - service_watcher
# Deployment specifications
deploy:
  variables:
    hostspec: '<%= hosts.map { |h| "-H #{h.name}@#{h.address}" }.join(" ") %>'
    hostspec3: '<%= hosts.first(3).map { |h| "-H #{h.name}@#{h.address}" }.join(" ") %>'
    quorum: '<%= hosts.map(&:name).join(",") %>'
    zkquorum: '<%= hosts.map { |h| "#{h.name}:2181" }.join(",") %>'
    flinkbootstrap: '<%= hosts.map { |h| "#{h.name}:9092" }.join(",") %>'
    haproxyservers: '<%= hosts.map { |h| "-s #{h.name}" }.join(" ") %>'
    firsthost: '<%= hosts.first.name %>'
  # Shared arguments to apply to all provision scripts
  shared_args:
  # List of provisioning steps.
  bootstrap:
    - hosts: $hostspec
    - ssh: $hostspec
  system:
    - sysctl:
    - apt:
    - java:
    - python:
    - swap:
    - ulimit:
  software:
    - kafka:
    - flink:
    - hbase:
    - zeppelin:
    - haproxy:
    - drbd:
    - spark:
  settings:
    - service_watcher: -z $zkquorum -F $firsthost
    - kafka: $hostspec
    - flink: -q $quorum -F $flinkbootstrap
    - hbase: -q $quorum
    - zeppelin:
    - haproxy: $haproxyservers
    - drbd: $hostspec3
  code:
    - service_watcher:
    - flink:
  # List of source folders to include in the ~/deploy directory when provision
  # Note that the *contents* of mentioned directories are copied in the deploy
  # directory
  bootstrap_folders:
    - source/shared
    - source/bootstrap
    - keys
  system_folders:
    - source/shared
    - source/system
  software_folders:
    - source/shared
    - source/software
  settings_folders:
    - source/shared
    - source/settings
  code_folders:
    - source/shared
    - source/code
  configure_folders:
    - source/shared
    - source/configure
# One-shot run command specifications
run:
  format_hdfs:
    command:
      - /usr/local/bin/drbd_service.sh start
      - ls /mnt/shared >&2
      - mkdir -p /mnt/shared/name
      - chown hbase:hbase -R /mnt/shared/name
      - sudo -u hbase /usr/local/hadoop/bin/hdfs namenode -format -force -nonInteractive
      - /usr/local/bin/drbd_service.sh stop
    mode: once
  format_data: rm -rf /home/hbase/dfs/data/VERSION /home/hbase/dfs/data/current
  format_zk: rm -rf /tmp/zookeeper
  fix_dpkg: dpkg --configure -a
  up_drbd: /usr/local/bin/drbd_service.sh up
# Hosts definitions
hosts:
  s1:
    <<: *host_defaults
    ip: 149.202.160.117
  s2:
    <<: *host_defaults
    ip: 149.202.160.12
  s3:
    <<: *host_defaults
    ip: 213.32.79.78
  s4:
    <<: *host_defaults
    ip: 213.32.79.60
  s5:
    <<: *host_defaults
    ip: 213.32.79.3
  s6:
    <<: *host_defaults
    ip: 213.32.79.62
  s7:
    <<: *host_defaults
    ip: 213.32.79.67
    configure:
      after:
        - create_topics: "-t paris -t london -t nyc"
        - hbase_tweets: "-t paris -t london -t nyc"
  s8:
    <<: *host_defaults
    ip: 213.32.79.73
  s9:
    <<: *host_defaults
    ip: 213.32.79.44
