# This file defines hostnames, usernames, ip addresses and private keys
# to use for connecting to the different servers using SSH.
#
# Default config options, referenced using YAML syntax
defaults:
    # Default options for hosts
    hosts: &host_defaults
        user: xnet     # Default non-privileged user
        key: keys/xnet # Identity file for SSH connection
# Hosts definitions
hosts:
    server-1:
        <<: *host_defaults
        ip: 213.32.77.17
    server-2:
        <<: *host_defaults
        ip: 213.32.77.173
    server-3:
        <<: *host_defaults
        ip: 213.32.77.170
# List of provisioning steps, follows the same conventions as vagrant-hosts.yml
provisioning:
    - apt:
    - java:
    - kafka:
    # Not yet functioning on non-vagrant hosts
    # - flink:
    # - hbase:
    # - zeppelin:
# List of source folders to include in the ~/deploy directory when provisioning
# Note that the *contents* of mentioned directories are copied in the deploy
# directory
source_folders:
    - source/install
