---
# Define the workers in the Vagrant testing environment
# Each entry defines the hostname of the machine
#
# Default config options, referenced using YAML syntax
defaults:
  # Default options for hosts
  hosts: &host_defaults
    user: vagrant     # Default non-privileged user
    memory: 2048      # Default RAM amount (MB)
# List of enabled services
services:
  - zookeeper
  - service_watcher
# Deployment specifications
deploy:
  variables:
    hostspec: '<%= hosts.map { |h| "-H #{h.name}@#{h.address}" }.join(" ") %>'
    quorum: '<%= hosts.map(&:name).join(",") %>'
    zkquorum: '<%= hosts.map { |h| "#{h.name}:2181" }.join(",") %>'
    flinkbootstrap: '<%= hosts.map { |h| "#{h.name}:9092" }.join(",") %>'
  # Shared arguments to apply to all provision scripts
  shared_args: -v # Using '-v' to indicate Vagrant provisioning
  # List of provisioning steps.
  bootstrap:
    - hosts: $hostspec
    - ssh: $hostspec
  system:
    - apt:
    - java:
    - python:
  software:
    - kafka:
    - flink:
    - hbase:
    - zeppelin:
  settings:
    - service_watcher: -z $zkquorum
    - kafka: $hostspec
    - flink: -q $quorum -F $flinkbootstrap
    - hbase: -q $quorum
    - zeppelin:
  code:
    - service_watcher:
    - flink:
  # List of source folders to include in the ~/deploy directory when provision
  # Note that the *contents* of mentioned directories are copied in the deploy
  # directory
  bootstrap_folders:
    - ../source/shared
    - ../source/bootstrap
    - .vagrant
  system_folders:
    - ../source/shared
    - ../source/system
  software_folders:
    - ../source/shared
    - ../source/software
  settings_folders:
    - ../source/shared
    - ../source/settings
  code_folders:
    - ../source/shared
    - ../source/code
  configure_folders:
    - ../source/shared
    - ../source/configure
# One-shot run command specifications
run:
  format_hdfs: /usr/local/hadoop/bin/hdfs namenode -format
# Hosts definitions
hosts:
  worker1:
    <<: *host_defaults
    key: .vagrant/machines/worker1/virtualbox/private_key
    ip: 10.20.1.100
    configure:
      after:
        - create_topics: "-t paris -t london -t nyc"
  worker2:
    <<: *host_defaults
    key: .vagrant/machines/worker2/virtualbox/private_key
    ip: 10.20.1.101
  worker3:
    <<: *host_defaults
    key: .vagrant/machines/worker3/virtualbox/private_key
    ip: 10.20.1.102
