---
zookeeper:
  quorum: zookeeper_quorum_replace_me
  timings:
    loop_tick: 0.5
    failed_loop_tick: 1.0
    partitioner_boundary: 1.0
    partitioner_reaction: 0.2
services:
  - name: haproxy
    type: global
  - name: kafka
    type: global
  - name: hadoop
    force:
      namenode: server-1
    prestart: |
      #!/bin/bash
      SRC=/etc/hosts.tpl
      DEST=/etc/hosts
      IP=$(getent hosts {instance:hadoop@namenode} | awk '{print $1}')
      sed "s#nn_ip#${IP}#" $SRC > $DEST
    instances:
      namenode: 1
      datanode: 3
  - name: hbase
    prestart: |
      #!/bin/bash
      SRC=/etc/hosts.tpl
      DEST=/etc/hosts
      IP=$(getent hosts {instance:hadoop@namenode} | awk '{print $1}')
      sed "s#nn_ip#${IP}#" $SRC > $DEST
    exclusive: true
    instances:
      master: 1
      regionserver: 2
  - name: zeppelin
    count: 2
  # - name: flink_city
  #   instances:
  #     paris: 1
  #     nyc: 1
  #     london: 1
  # - name: flink_producer_fake
  #   count: 1
