---
zookeeper:
  quorum: zookeeper_quorum_replace_me
  timings:
    loop_tick: 1.5
    failed_loop_tick: 3.0
    partitioner_boundary: 5.0
    partitioner_reaction: 2.0
services:
  - name: haproxy
    type: global
  - name: kafka
    type: global
  - name: flink
    prestart: &jobscript |
      #!/bin/bash
      SRC=/usr/local/flink/conf/flink-conf.yaml.tpl
      DEST=/usr/local/flink/conf/flink-conf.yaml
      sed "s#jobmanager_replace_me#{instance:flink@jobmanager}#" $SRC > $DEST
    instances:
      jobmanager: 1
      taskmanager: 3
  - name: hadoop
    prestart: &hostscript |
      #!/bin/bash
      SRC=/etc/hosts.tpl
      DEST=/etc/hosts
      IP=$(getent hosts {instance:hadoop@namenode} | awk '{print $1}')
      sed "s#nn_ip#${IP}#" $SRC > $DEST
    instances:
      namenode: 1
      datanode: 5
  - name: hbase
    prestart: *hostscript
    exclusive: true
    instances:
      master: 1
      regionserver: 6
  - name: zeppelin
    prestart: |
      #!/bin/bash
      SRC=/etc/hosts.tpl
      DEST=/etc/hosts
      IP=$(getent hosts {instance:hadoop@namenode} | awk '{print $1}')
      sed "s#nn_ip#${IP}#" $SRC > $DEST
    count: 2
  - name: flink_city
    prestart: *jobscript
    instances:
      paris: 1
      nyc: 1
      london: 1
  # - name: flink_city_console
  #   prestart: *jobscript
  #   enabled: false
  #   instances:
  #     paris: 1
  #     nyc: 1
  #     london: 1
  - name: flink_producer_fake
    prestart: *jobscript
    enabled: false
    count: 1
  - name: flink_producer
    prestart: *jobscript
    count: 1
