---
zookeeper:
  quorum: zookeeper_quorum_replace_me
  timings:
    loop_tick: 0.5
    failed_loop_tick: 1.0
    partitioner_boundary: 5.0
    partitioner_reaction: 1.0
services:
  # begin dummy services
  # - name: dummy_global
  #   type: global
  # - name: dummy_shared
  #   count: 2
  # - name: dummy_multi
  #   instances:
  #     '1': 1
  #     '2': 2
  #     '3': 3
  # begin actual services
  # - name: haproxy
  #   type: global
  # - name: kafka
  #   type: global
  - name: bookkeeper
    type: global
  - name: hadoop
    prestart: |
      #!/bin/bash
      NAMENODES="{instance:hadoop@namenode}"
      DEST=/usr/local/hadoop/etc/hadoop/hdfs-site.xml
      SRC=/usr/local/hadoop/etc/hadoop/hdfs-site.xml.tpl
      if grep ',' <<<"$NAMENODES" >/dev/null ; then
        # We have two namenodes
        IFS=',' read -r -a NN <<< "$NAMENODES"
        sed "s#nn1#${NN[0]}#" ${SRC}2 > $DEST
        sed -i "s#nn2#${NN[1]}#" $DEST
      else
        # We only have one namenode
        sed "s#nn1#${NAMENODES}#" ${SRC}1 > $DEST
      fi
    instances:
      namenode: 2
      datanode: 3
  # - name: hbase
  #   prestart: |
  #     #!/bin/bash
  #     NAMENODES="{instance:hadoop@namenode}"
  #     DEST=/usr/local/hbase/conf/hbase-site.xml
  #     SRC=/usr/local/hbase/conf/hbase-site.xml.tpl
  #     if grep ',' <<<"$NAMENODES" >/dev/null ; then
  #       # We have two namenodes
  #       IFS=',' read -r -a NN <<< "$NAMENODES"
  #       sed "s#nn1#${NN[0]}#" ${SRC}2 > $DEST
  #       sed -i "s#nn2#${NN[1]}#" $DEST
  #     else
  #       # We only have one namenode
  #       sed "s#nn1#${NAMENODES}#" ${SRC}1 > $DEST
  #     fi
  #   exclusive: true
  #   instances:
  #     master: 1
  #     regionserver: 2
  # - name: zeppelin
  #   count: 2
  # - name: flink_city
  #   instances:
  #     paris: 1
  #     nyc: 1
  #     london: 1
  # - name: flink_producer_fake
  #   count: 1
