---
zookeeper:
  quorum: zookeeper_quorum_replace_me
  timings:
    loop_tick: 0.5
    failed_loop_tick: 1.0
    partitioner_boundary: 1.0
    partitioner_reaction: 0.2
services:
  # begin dummy services
  - name: dummy_global
    enabled: false
    type: global
  - name: dummy_shared
    enabled: false
    count: 2
  - name: dummy_multi
    enabled: false
    instances:
      '1': 1
      '2': 2
      '3': 3
  # begin actual services
  - name: haproxy
    type: global
  - name: kafka
    type: global
  - name: flink
    prestart: |
      #!/bin/bash
      SRC=/usr/local/flink/conf/flink-conf.yaml.tpl
      DEST=/usr/local/flink/conf/flink-conf.yaml
      sed "s#jobmanager_replace_me#{instance:flink@jobmanager}#" $SRC > $DEST
    instances:
      jobmanager: 1
      taskmanager: 1
  - name: hadoop
    force:
      namenode: replace_me_first_host
    prestart: &hostscript |
      #!/bin/bash
      SRC=/etc/hosts.tpl
      DEST=/etc/hosts
      IP=$(getent hosts {instance:hadoop@namenode} | awk '{print $1}')
      sed "s#nn_ip#${IP}#" $SRC > $DEST
    instances:
      namenode: 1
      datanode: 1
  - name: hbase
    prestart: *hostscript
    exclusive: true
    instances:
      master: 1
      regionserver: 1
  - name: zeppelin
    count: 1
  - name: flink_city
    enabled: false
    instances:
      paris: 1
      nyc: 1
      london: 1
  - name: flink_city_console
    instances:
      paris: 1
      nyc: 1
      london: 1
  - name: flink_producer_fake
    count: 1
