---
zookeeper:
  quorum: zookeeper_quorum_replace_me
  timings:
    loop_tick: 0.5
    failed_loop_tick: 1.0
    partitioner_boundary: 1.0
    partitioner_reaction: 0.2
services:
  # begin dummy services
  - name: dummy_global
    type: global
  - name: dummy_shared
    count: 2
  - name: dummy_multi
    instances:
      '1': 1
      '2': 2
      '3': 3
  # begin actual services
  - name: kafka
    type: global
  - name: hadoop
    instances:
      namenode: 1
      secondarynamenode: 2
      datanode: 3
  - name: hbase
    exclusive: true
    instances:
      master: 1
      regionserver: 2
  - name: zeppelin
    count: 2
  - name: flink_city
    instances:
      paris: 1
      nyc: 1
      london: 1
  - name: flink_producer_fake
    count: 1
