---
zookeeper:
  quorum: zookeeper_quorum_replace_me
services:
  - name: dummy_global
    type: global
  - name: dummy_shared
    count: 2
  - name: dummy_multi
    instances:
      '1': 1
      '2': 2
      '3': 3
